packages:
  - console
  - docs
  - e2e
  - packages/*
  - apps/*

inject-workspace-packages: true

onlyBuiltDependencies:
  - cypress

overrides:
  '@typescript-eslint/parser': '^8.35.1'

sideEffectsCache: false
