services:
  traefik:
    extra_hosts:
      - host.docker.internal:host-gateway
  setup:
    environment:
      LOGIN_BASE_URL: https://localhost/ui/v2/login/
      ZITADEL_API_INTERNAL_URL: http://zitadel:8080
      ZITADEL_API_URL: https://localhost
      ZITADEL_API_DOMAIN: localhost
    volumes:
      - pat:/pat # Read the PAT file from zitadels setup
      - ./env:/acceptance-env # Write the environment variables file for the tests
      - ../login:/login-env # Write the environment variables file for the login
