name: 💡 Proposal / Feature request
description: "Create an issue for a feature request/proposal."
labels: ["enhancement"]
type: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this proposal / feature reqeust
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this proposal?
      options:
      - I don't know
      - Low (it can wait)
      - Medium (it should be backlogged)
      - High (it should be prioritized)
      - Critical (it should be worked on immediately)
    validations:
      required: true
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
      - label:
          I could not find a solution in the existing issues, docs, nor discussions
        required: true
      - label:
          I have joined the [ZITADEL chat](https://zitadel.com/chat)
  - type: textarea
    id: problem
    attributes:
      label: Describe your problem
      description: Please describe your problem this proposal / feature is supposed to solve.
      placeholder: Describe the problem you have.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: Which solution do you propose?
      placeholder: As a [type of user], I want [some goal] so that [some reason].
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of ZITADEL are you using.
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: How do you use ZITADEL?
      options:
      - ZITADEL Cloud
      - Self-hosted
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Please add any other infos that could be useful.
  - type: markdown
    attributes:
        value: |
            ## Vote for this issue
            If you come accross this issue and would like to see it taken care of, please vote with a thumbs up 👍.
            If you have any additional thoughts or use cases, please leave a comment.
