services:
  devcontainer:
    container_name: devcontainer-login-integration
    env_file: ../../apps/login/.env.test
    network_mode: host
  depends_on:
    login-integration:
      condition: service_healthy

  login-integration:
    container_name: login-integration
    image: "${LOGIN_TAG:-zitadel-login:local}"
    env_file: ../../apps/login/.env.test
    network_mode: host
    environment:
      NODE_ENV: test
      PORT: 3001
      NEXT_PUBLIC_BASE_PATH: /ui/v2/login
    depends_on:
      mock-zitadel:
        condition: service_started

  mock-zitadel:
    container_name: mock-zitadel
    build:
      context: ../../apps/login/integration/core-mock
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
