services:

  devcontainer:
    container_name: devcontainer
    build:
      context: .
    volumes:
      - ../:/workspaces/zitadel:cached
    command: sleep infinity
    working_dir: /workspaces/zitadel
    env_file:
      - .env.api
      - .env.login
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      DEVCONTAINER_LOGIN_CORE_MOCK_HOST: login-api-mock

  db:
    container_name: db
    image: postgres:17.0-alpine3.19
    restart: unless-stopped
    env_file:
      - ./.env.db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - 5432:5432

  api-init:
    container_name: api-init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../:/workspaces/zitadel:cached
    command: init --config /workspaces/zitadel/.devcontainer/zitadel.yaml
    env_file:
      - path: .env.api
        required: true
      - path: ../${CORE_ENV_FILE:-none}
        required: false
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    healthcheck:
      test:
        - CMD
        - /app/zitadel
        - ready
        - --config
        - /workspaces/zitadel/.devcontainer/zitadel.yaml
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  api-setup:
    container_name: api-setup
    depends_on:
      api-init:
        condition: service_completed_successfully
    volumes:
      - ../:/workspaces/zitadel:cached
    command: setup --config /workspaces/zitadel/.devcontainer/zitadel.yaml --steps /workspaces/zitadel/.devcontainer/zitadel.yaml --masterkey MasterkeyNeedsToHave32Characters
    env_file:
      - path: .env.api
        required: true
      - path: ../${CORE_ENV_FILE:-none}
        required: false
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    healthcheck:
      test:
        - CMD
        - /app/zitadel
        - ready
        - --config
        - /workspaces/zitadel/.devcontainer/zitadel.yaml
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  api:
    container_name: api
    depends_on:
      api-setup:
        condition: service_completed_successfully
    volumes:
      - ../:/workspaces/zitadel:cached
    command: start --config /workspaces/zitadel/.devcontainer/zitadel.yaml --masterkey MasterkeyNeedsToHave32Characters
    env_file:
      - path: .env.api
        required: true
      - path: ../${CORE_ENV_FILE:-none}
        required: false
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    develop:
      watch:
        - path: ../zitadel
          action: rebuild
    ports:
      - "8080:8080"
    healthcheck:
      test:
        - CMD
        - /app/zitadel
        - ready
        - --config
        - /workspaces/zitadel/.devcontainer/zitadel.yaml
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  login:
    container_name: login
    build:
      context: ../apps/login
    develop:
      watch:
        - path: ../apps/login/.next/standalone
          action: "rebuild"
    ports:
      - "3000:3000"
    volumes:
      - ../:/workspaces/zitadel:cached
    env_file:
      - path: .env.login
        required: true
      - path: ../${LOGIN_ENV_FILE:-none}
        required: false
    depends_on:
      api-setup:
        condition: service_completed_successfully

  login-api-mock:
    container_name: login-api-mock
    build:
      context: ../apps/login/integration/api-mock
      additional_contexts:
        zitadel-protos: ../proto
    develop:
      watch:
        - path: ../apps/login/integration/api-mock
          action: "rebuild"
        - path: ../protos
          action: "rebuild"
    ports:
      - 22220:22220
      - 22222:22222

volumes:
  db-data:
