services:

  devcontainer:
    container_name: devcontainer
    build:
      context: .
    volumes:
      - ../:/workspaces/zitadel:cached
    command: sleep infinity
    working_dir: /workspaces/zitadel
    environment:
      DEVCONTAINER_DB_HOST: db
      DEVCONTAINER_LOGIN_CORE_MOCK_HOST: login-core-mock

  db:
    container_name: zitadel-db
    image: postgres:17.0-alpine3.19
    restart: unless-stopped
    env_file:
      - ./postgres.env
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - db-data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - 5432:5432

  login-core-mock:
    container_name: login-core-mock
    image: "apps-login-integration-core-mock"
    build:
      context: ../apps/login/integration/core-mock
      additional_contexts:
        - zitadel-protos=../proto
    ports:
      - 22220:22220
      - 22222:22222

volumes:
  db-data:
