name: ZITADEL CI/CD

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  actions: write

jobs:

  check:
    uses: ./.github/workflows/check.yml
    with:
      node_version: "22"

  api:
    uses: ./.github/workflows/api.yml
    with:
      node_version: "20"
      buf_version: "latest"

  console:
    uses: ./.github/workflows/console.yml
    with:
      node_version: "20"

  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: "23.0.7"
      dry_run: true

  compile:
    needs: [api, console, version]
    uses: ./.github/workflows/compile.yml
    with:
      api_cache_key: ${{ needs.api.outputs.cache_key }}
      console_cache_key: ${{ needs.console.outputs.cache_key }}
      api_cache_path: ${{ needs.api.outputs.cache_path }}
      console_cache_path: ${{ needs.console.outputs.cache_path }}
      version: ${{ needs.version.outputs.version }}
      node_version: "20"

  api-unit-test:
    needs: api
    uses: ./.github/workflows/api-unit-test.yml
    with:
      api_cache_key: ${{ needs.api.outputs.cache_key }}
      api_cache_path: ${{ needs.api.outputs.cache_path }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  api-integration-test:
    needs: api
    uses: ./.github/workflows/api-integration-test.yml
    with:
      api_cache_key: ${{ needs.api.outputs.cache_key }}
      api_cache_path: ${{ needs.api.outputs.cache_path }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    needs: [api]
    uses: ./.github/workflows/lint.yml
    with:
      buf_version: "latest"
      go_lint_version: "latest"
      api_cache_key: ${{ needs.api.outputs.cache_key }}
      api_cache_path: ${{ needs.api.outputs.cache_path }}

  container:
    needs: [compile]
    uses: ./.github/workflows/container.yml
    secrets: inherit
    permissions:
      packages: write
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      node_version: "22"
      build_image_name_api: "ghcr.io/zitadel/zitadel-build"
      build_image_name_login: "ghcr.io/zitadel/zitadel-login-build"

  e2e:
    uses: ./.github/workflows/e2e.yml
    needs: [compile]

  release:
    uses: ./.github/workflows/release.yml
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    needs:
      [
        version,
        api-unit-test,
        api-integration-test,
        lint,
        check,
        container,
        e2e,
      ]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    secrets:
      GCR_JSON_KEY_BASE64: ${{ secrets.GCR_JSON_KEY_BASE64 }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      build_image_name: ${{ needs.container.outputs.build_image_api }}
      semantic_version: "23.0.7"
      image_name: "ghcr.io/zitadel/zitadel"
      google_image_name: "europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel"
      build_image_name_login: ${{ needs.container.outputs.build_image_login }}
      image_name_login: "ghcr.io/zitadel/zitadel-login"
      google_image_name_login: "europe-docker.pkg.dev/zitadel-common/zitadel-repo/zitadel-login"
