name: Check

on: 
  workflow_call: 
    inputs:
      node_version:
        required: true
        type: string
    outputs:
      nx_cache_key:
        value: ${{ jobs.check.outputs.nx_cache_key }}
      nx_cache_path:
        value: ${{ jobs.check.outputs.nx_cache_path }}

env:
  nx_cache_path: .nx

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    outputs:
      nx_cache_key: ${{ steps.nx_cache.outputs.cache-primary-key }}
      nx_cache_path: ${{ env.nx_cache_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Restore Nx cache
        uses: actions/cache/restore@v4
        id: nx_cache
        with:
          path: ${{ env.nx_cache_path }}
          key: nx-${{ runner.os }}-${{ github.event.pull_request.base.ref }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ github.event.pull_request.base.ref }}-
            nx-${{ runner.os }}-
      - name: Install global modules
        run: pnpm add -g nx sass
      - name: Install Cypress binary
        run: pnpm cypress install
        working-directory: apps/login
      - uses: nrwl/nx-set-shas@v4
      - name: Lint, Build, Unit Tests
        run: nx affected --targets lint test-unit generate build --exclude @zitadel/docs,@zitadel/benchmark
      - uses: actions/cache/save@v4
        with:
          key: ${{ steps.nx_cache.outputs.cache-primary-key }}
          path: ${{ env.nx_cache_path }}
      - name: Login Integration Tests
        run: pnpm --filter @zitadel/login test-integration