name: Integration test core

on: 
  workflow_call: 
    inputs:
      login_build_image:
        required: true
        type: string
      node_version:
        required: true
        type: string

permissions:
  packages: write

jobs:
  login-integration-test:
    name: login-integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js without caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install and cache dependencies including Cypress binaries
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - name: Run Integration Tests against the Login and a Mocked Zitadel API
        run: pnpm nx test:integration login
