name: Integration test core

on: 
  workflow_call: 
    inputs:
      node_version:
        required: true
        type: string

permissions:
  packages: write

jobs:
  login-integration-test:
    name: login-integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/login/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('apps/login/**/*.js', 'apps/login/**/*.jsx', 'apps/login/**/*.ts', 'apps/login/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-
      - name: Install Cypress binary
        run: pnpm cypress install
        working-directory: apps/login
      - name: Run Integration Tests against the Login and a Mocked Zitadel API
        run: pnpm nx test:integration login
