name: Integration test core

on: 
  workflow_call: 
    inputs:
      login_build_image:
        required: true
        type: string

permissions:
  packages: write

jobs:
  login-integration-test:
    name: login-integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli@0.80.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run Integration Tests against the Login and a Mocked Zitadel API
        run: npm run devcontainer:integration:login:up
        env:
          LOGIN_TAG: ${{ inputs.login_build_image }}
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
          # Add verbose logging
          COMPOSE_LOG_LEVEL: DEBUG
          DEVCONTAINER_LOG_LEVEL: trace
