name: Integration test core

on: 
  workflow_call: 
    inputs:
      login_build_image:
        required: true
        type: string
      node_version:
        required: true
        type: string

permissions:
  packages: write

jobs:
  login-integration-test:
    name: login-integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli@0.80.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pull Login Build Image
        run: docker compose --file .devcontainer/login-integration/docker-compose.yaml pull
        env:
          LOGIN_TAG: ${{ inputs.login_build_image }}
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Run Integration Tests against the Login and a Mocked Zitadel API
        run: pnpm nx test:integration login
        env:
          LOGIN_TAG: ${{ inputs.login_build_image }}
          DOCKER_BUILDKIT: 1
