name: Integration test core

on: 
  workflow_call: 
    inputs:
      login_build_image:
        required: true
        type: string
      node_version:
        required: true
        type: string

permissions:
  packages: write

jobs:
  login-integration-test:
    name: login-integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js with caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/login/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install Cypress binary
        run: pnpm cypress install
        working-directory: apps/login
      - name: Run Integration Tests against the Login and a Mocked Zitadel API
        run: pnpm nx test:integration login
