name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ls -lah turbo.json   .npmrc   package.json   pnpm-lock.yaml   pnpm-workspace.yaml
      - name: Set up persistent Buildx builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          use: true
      - run: ls -lah turbo.json   .npmrc   package.json   pnpm-lock.yaml   pnpm-workspace.yaml
      - name: Build
        uses: docker/bake-action@v6
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.output=type=docker
      - run: ls -lah turbo.json   .npmrc   package.json   pnpm-lock.yaml   pnpm-workspace.yaml
      - name: Run
        run: make login-lint
