name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        # We enable the containerd image store, so the buildx driver of type docker can cache-export build layers.
        # The driver docker-container has many cache misses, as it stores its state in an ephemeral docker volume.
        # This state is only populated after the first build, but the docker build layer cache depends on it.
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/zitadel/login
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up persistent Buildx builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/bake-action@v6
        env:
          # latest if branch is main, otherwise image version which is the pull request number
          BUILD_CACHE_KEY: ${{ github.ref == 'refs/heads/main' && 'latest' || fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        with:
          source: .
          targets: login-pnpm,login-dev-base,login-lint
          provenance: false
          files: |
            docker-bake.hcl
            docker-bake-ci.hcl
