name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Set up persistent Buildx builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          use: true
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: Build
      - name: Cache
        uses: actions/cache@v3
        id: pnpm-store-cache
        with:
          path: |
            pnpm
          key: pnpm-cache-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-cache-

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-map: |
            {
              "pnpm": "/pnpm"
            }
          skip-extraction: ${{ steps.pnpm-store-cache.outputs.cache-hit }}
      - name: Build
        uses: docker/bake-action@v6
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          targets: login-lint
      - name: Run
        run: make login-lint
