name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - run: make quality
