name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Set up persistent Buildx builder
        uses: docker/setup-buildx-action@v3
      - run: docker buildx du
      - name: Build
        uses: docker/bake-action@v6
        with:
          push: false
      - name: Run
        run: make login-lint
      - run: docker buildx du
