name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Restore GHA Build Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref_name }}
          restore-keys: |
            buildx-
      - name: Build via Make (docker-bake.hcl uses type=gha)
        env:
          BUILDKIT_CACHE_DIR: /tmp/.buildx-cache
        run: make login-quality
