name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Set up persistent Buildx builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          use: true
      - name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          targets: login-lint
