name: Quality
on:
  pull_request:
jobs:
  quality:
    name: Ensure Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Set up persistent Buildx builder
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
      - run: docker buildx du -v
      - name: Build via Make
        run: make login-lint
